### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by UnknownNull** [funniray/waterdog-pureperms#2]
WDPE 1.2.4

**Comment by UnknownNull** [comment]
https://github.com/fernanACM/PurePerms
This fork supports mysql.

**Comment by funniray** [comment]
should work with any version of pureperms that supports mysql. This was just a quick thing thrown together to just allow PurePerms permissions to load on waterdogPE and nothing else. I wouldn't recommend using this plugin if you're not currently using pureperms on a pmmp server.

In regards to it not working on wdpe 1.2.4, just set `showpiracywarning` to false in the config.yml

**Comment by UnknownNull** [comment]
The reason why the player's login to the server is slow is the same errors in the console?

**Comment by funniray** [comment]
Can you please include the errors you have in console?

**Comment by UnknownNull** [comment]
I tested it on an older version of WDPE which was like this.
And in the new version it is not applicable at all

**Comment by funniray** [comment]
I'm really sorry, but you're going to have to explain the issue you have a lot more, in detail, including error messages and with steps to reproduce the issue that you're having.

**Comment by UnknownNull** [comment]
`2023-03-24 22:44:09.401 [WaterdogPE-main] ERROR - Error while loading plugin main class(main=com.funniray.wdpureperms.WdPureperms,plugin=Pureperms-WDPE)
java.lang.ClassNotFoundException: com.funniray.wdpureperms.WdPureperms
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at dev.waterdog.waterdogpe.plugin.PluginClassLoader.findClass(PluginClassLoader.java:58) ~[Waterdog.jar:?]
	at dev.waterdog.waterdogpe.plugin.PluginClassLoader.findClass(PluginClassLoader.java:41) ~[Waterdog.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at dev.waterdog.waterdogpe.plugin.PluginLoader.loadPluginJAR(PluginLoader.java:52) ~[Waterdog.jar:?]
	at dev.waterdog.waterdogpe.plugin.PluginManager.loadPlugin(PluginManager.java:101) ~[Waterdog.jar:?]
	at java.util.TreeMap.forEach(TreeMap.java:1282) ~[?:?]
	at dev.waterdog.waterdogpe.plugin.PluginManager.loadPluginsIn(PluginManager.java:78) ~[Waterdog.jar:?]
	at dev.waterdog.waterdogpe.plugin.PluginManager.<init>(PluginManager.java:52) ~[Waterdog.jar:?]
	at dev.waterdog.waterdogpe.ProxyServer.<init>(ProxyServer.java:166) ~[Waterdog.jar:?]
	at dev.waterdog.waterdogpe.WaterdogPE.main(WaterdogPE.java:63) ~[Waterdog.jar:?]`

**Comment by funniray** [comment]
Seems like the version of my plugin you downloaded is corrupt? I'm not quite sure. Please try downloading it again from the releases here: https://github.com/funniray/waterdog-pureperms/releases/tag/v0.5.0

It seems to load fine on my own machine, which is running on Java 17, with WaterdogPE 1.2.4

**Comment by UnknownNull** [comment]
Im run java 17
But show this error.
You test by mysql?
Idn...🤷 I don't know anything about Java

**Comment by funniray** [comment]
I'm sorry, but if you've re-downloaded the plugin, but are still getting the `java.lang.ClassNotFoundException: com.funniray.wdpureperms.WdPureperms`, I'm unsure what I can do to help you. That error would imply that `WdPureperms.class` doesn't exist inside the plugin's .jar file.

A .jar file is just a .zip file and you should be able to either rename it to a .zip or open it with a tool like 7zip or winrar double check that inside the `com/funniray/wdpureperms` that WdPureperms.class exists.

**Comment by UnknownNull** [comment]
![Uploading Screenshot_20230325-022640_Microsoft Remote Desktop.jpg…]()

**Comment by funniray** [comment]
Sorry, that image appears to be broken

**Comment by UnknownNull** [comment]
![Screenshot_20230325-022640_Microsoft Remote Desktop](https://user-images.githubusercontent.com/91208232/227704458-3597c7a2-1e94-4a1b-8ba8-c2478c4cecad.jpg)

**Comment by UnknownNull** [comment]
![image](https://user-images.githubusercontent.com/91208232/227718740-2470f4ca-a656-4237-8485-42c6b700b923.png)

**Comment by UnknownNull** [comment]
edited

**Comment by funniray** [comment]
Try this release
https://github.com/funniray/waterdog-pureperms/releases/tag/v0.6.0

**Comment by UnknownNull** [comment]
Thanks for updated

**Comment by UnknownNull** [comment]
Plugin enabled but not worked

**Comment by funniray** [comment]
all it does is add permissions from the existing pureperms DB to players on waterdogPE. Permissions are only calculated when the player joins the proxy. 

This plugin does not add any commands and does not ever modify the pureperms database.

How are you testing to see if the plugin is working?

**Comment by UnknownNull** [comment]
I used to use the previous version and it correctly gave the permissions to the players, but this time apparently it doesn't do it, but I will test more.
